flowchart TB
    subgraph " "
    v0["channel.fromPath"]
    v5["ch_fasta_fai"]
    end
    v2(["SAMTOOLS_INDEX"])
    subgraph " "
    v3[" "]
    v7[" "]
    v8["stats"]
    v10[" "]
    v11["flagstat"]
    v13[" "]
    v14["idxstats"]
    end
    subgraph "BAM_STATS_SAMTOOLS [BAM_STATS_SAMTOOLS]"
    v6(["SAMTOOLS_STATS"])
    v9(["SAMTOOLS_FLAGSTAT"])
    v12(["SAMTOOLS_IDXSTATS"])
    end
    v1(( ))
    v0 --> v1
    v1 --> v2
    v2 --> v3
    v2 --> v1
    v5 --> v6
    v1 --> v6
    v6 --> v8
    v6 --> v7
    v1 --> v9
    v9 --> v11
    v9 --> v10
    v1 --> v12
    v12 --> v14
    v12 --> v13
