flowchart TB
    subgraph " "
    v0["vcf_ch"]
    v1["fasta_ch"]
    v2["fai_ch"]
    v3["dict_ch"]
    v4["empty_ch"]
    v9["channel.empty"]
    end
    v5(["GATK4_SVANNOTATE"])
    subgraph " "
    v6[" "]
    v7[" "]
    v8[" "]
    v10[" "]
    end
    v0 --> v5
    v1 --> v5
    v2 --> v5
    v3 --> v5
    v4 --> v5
    v5 --> v8
    v5 --> v7
    v5 --> v6
    v9 --> v10
