flowchart TB
    subgraph " "
    v0["fasta"]
    v1["targets"]
    v2["antitargets"]
    v6["channel.empty"]
    end
    v3(["CNVKIT_REFERENCE"])
    subgraph " "
    v4[" "]
    v5[" "]
    v7[" "]
    end
    v0 --> v3
    v1 --> v3
    v2 --> v3
    v3 --> v5
    v3 --> v4
    v6 --> v7
