flowchart TB
    subgraph " "
    v0["tumor_bam_ch"]
    v8["control_bam_ch"]
    v36["fasta_ch"]
    v37["simple_repeat_bed"]
    v38["simple_repeat_bed_index"]
    v39["control_panel_files"]
    end
    v1(["NANOMONSV_PARSE_TUMOR"])
    subgraph " "
    v2[" "]
    v3[" "]
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    v10[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v41[" "]
    v42[" "]
    v43[" "]
    v44[" "]
    v45[" "]
    v46[" "]
    end
    v9(["NANOMONSV_PARSE_CONTROL"])
    v40(["NANOMONSV_GET"])
    v16(( ))
    v24(( ))
    v0 --> v1
    v0 --> v16
    v1 --> v7
    v1 --> v6
    v1 --> v5
    v1 --> v4
    v1 --> v3
    v1 --> v2
    v1 --> v16
    v8 --> v9
    v8 --> v24
    v9 --> v15
    v9 --> v14
    v9 --> v13
    v9 --> v12
    v9 --> v11
    v9 --> v10
    v9 --> v24
    v36 --> v40
    v37 --> v40
    v38 --> v40
    v39 --> v40
    v16 --> v40
    v24 --> v40
    v40 --> v46
    v40 --> v45
    v40 --> v44
    v40 --> v43
    v40 --> v42
    v40 --> v41
