flowchart TB
    subgraph " "
    v0["in_ch"]
    v5["channel.empty"]
    end
    v1(["VARSCAN_SOMATIC"])
    subgraph " "
    v2[" "]
    v3[" "]
    v4[" "]
    v6[" "]
    end
    v0 --> v1
    v1 --> v4
    v1 --> v3
    v1 --> v2
    v5 --> v6
