flowchart TB
    subgraph " "
    v0["input_ch"]
    v1["fasta_ch"]
    v6["channel.empty"]
    end
    v2(["BCFTOOLS_MERGE"])
    subgraph " "
    v3[" "]
    v4[" "]
    v5[" "]
    v7[" "]
    end
    v0 --> v2
    v1 --> v2
    v2 --> v5
    v2 --> v4
    v2 --> v3
    v6 --> v7
