flowchart TB
    subgraph " "
    v0[" "]
    end
    v1(["UNTAR"])
    subgraph " "
    v2[" "]
    v5[" "]
    v6["database"]
    end
    v4(["MMSEQS_TSV2EXPROFILEDB"])
    v3(( ))
    v0 --> v1
    v1 --> v2
    v1 --> v3
    v3 --> v4
    v4 --> v6
    v4 --> v5
