flowchart TB
    subgraph " "
    v0["bam_ch"]
    v1["sort_order"]
    v5["fasta_ch"]
    v6["filter"]
    end
    v2(["PICARD_SORTSAM"])
    subgraph " "
    v3[" "]
    v8[" "]
    v9[" "]
    v10[" "]
    end
    v7(["PICARD_FILTERSAMREADS"])
    v4(( ))
    v0 --> v2
    v1 --> v2
    v2 --> v3
    v2 --> v4
    v5 --> v7
    v6 --> v7
    v4 --> v7
    v7 --> v10
    v7 --> v9
    v7 --> v8
