flowchart TB
    subgraph " "
    v0["in_ch"]
    end
    v1(["FGBIO_COLLECTDUPLEXSEQMETRICS"])
    subgraph " "
    v2[" "]
    v3[" "]
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    end
    v0 --> v1
    v1 --> v9
    v1 --> v8
    v1 --> v7
    v1 --> v6
    v1 --> v5
    v1 --> v4
    v1 --> v3
    v1 --> v2
