flowchart TB
    subgraph " "
    v0["fasta_ch"]
    v1["get_sizes"]
    v7[" "]
    v9["in_ch"]
    end
    v2(["SAMTOOLS_FAIDX"])
    subgraph " "
    v3[" "]
    v4[" "]
    v5[" "]
    v6[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    end
    v10(["WHATSHAP_PHASE"])
    v8(( ))
    v0 --> v2
    v1 --> v2
    v2 --> v6
    v2 --> v5
    v2 --> v4
    v2 --> v3
    v2 --> v8
    v7 --> v8
    v9 --> v10
    v8 --> v10
    v10 --> v13
    v10 --> v12
    v10 --> v11
