flowchart TB
    subgraph " "
    v0["vcf_ch"]
    v1["regions"]
    v2["targets"]
    v3["samples"]
    v8["channel.empty"]
    end
    v4(["BCFTOOLS_CALL"])
    subgraph " "
    v5[" "]
    v6[" "]
    v7[" "]
    v9[" "]
    end
    v0 --> v4
    v1 --> v4
    v2 --> v4
    v3 --> v4
    v4 --> v7
    v4 --> v6
    v4 --> v5
    v8 --> v9
