flowchart TB
    subgraph " "
    v0["channel.of"]
    v2["fasta_ch"]
    v3["cram_ch"]
    v4["fai_ch"]
    end
    v5(["MANTA_TUMORONLY"])
    subgraph " "
    v6[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    v10[" "]
    v11[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v16[" "]
    end
    v12(["MANTA_CONVERTINVERSION"])
    v1(( ))
    v0 --> v1
    v2 --> v5
    v2 --> v12
    v3 --> v5
    v4 --> v5
    v1 --> v5
    v5 --> v11
    v5 --> v10
    v5 --> v9
    v5 --> v8
    v5 --> v12
    v5 --> v7
    v5 --> v6
    v12 --> v16
    v12 --> v15
    v12 --> v14
    v12 --> v13
