flowchart TB
    subgraph " "
    v0["channel.empty"]
    v2["channel.empty"]
    v4["channel.empty"]
    v6["channel.empty"]
    v8["channel.empty"]
    v10["ch_dedup_input"]
    v11["get_output_stats"]
    v17[" "]
    v24["ch_fasta_fai"]
    v25["ch_bam"]
    v26["index_format"]
    v45["get_output_stats"]
    v52[" "]
    v65["ch_fasta_fai"]
    v66["index_format"]
    end
    subgraph " "
    v1["ch_tsv_edit_distance"]
    v3["ch_tsv_per_umi"]
    v5["ch_tsv_umi_per_position"]
    v7["ch_genomic_dedup_log"]
    v9["ch_transcriptomic_dedup_log"]
    v13[" "]
    v15[" "]
    v19[" "]
    v21[" "]
    v23[" "]
    v28[" "]
    v29[" "]
    v30[" "]
    v31[" "]
    v33[" "]
    v36[" "]
    v37["stats"]
    v39[" "]
    v40["flagstat"]
    v42[" "]
    v43["idxstats"]
    v47[" "]
    v48["transcriptomic_dedup_log"]
    v50[" "]
    v54[" "]
    v56[" "]
    v58[" "]
    v60["tsv_edit_distance"]
    v62["tsv_per_umi"]
    v64["tsv_umi_per_position"]
    v68[" "]
    v69[" "]
    v70[" "]
    v71[" "]
    v75[" "]
    v76["prepare_for_rsem_log"]
    v78["transcriptome_bam"]
    v83["multiqc_files"]
    v88["per_sample_mqc_bundle"]
    v90["stats"]
    v92["flagstat"]
    v94["idxstats"]
    end
    subgraph "BAM_DEDUP_UMI [BAM_DEDUP_UMI]"
    subgraph "BAM_DEDUP_UMI:BAM_DEDUP_STATS_SAMTOOLS_UMITOOLS_GENOME [BAM_DEDUP_STATS_SAMTOOLS_UMITOOLS_GENOME]"
    v12(["UMITOOLS_DEDUP"])
    v14(["SAMTOOLS_INDEX"])
    subgraph "BAM_DEDUP_UMI:BAM_DEDUP_STATS_SAMTOOLS_UMITOOLS_GENOME:BAM_STATS_SAMTOOLS [BAM_STATS_SAMTOOLS]"
    v18(["SAMTOOLS_STATS"])
    v20(["SAMTOOLS_FLAGSTAT"])
    v22(["SAMTOOLS_IDXSTATS"])
    end
    v16(( ))
    end
    subgraph "BAM_DEDUP_UMI:BAM_SORT_STATS_SAMTOOLS [BAM_SORT_STATS_SAMTOOLS]"
    v27(["SAMTOOLS_SORT"])
    v32(["SAMTOOLS_INDEX"])
    subgraph "BAM_DEDUP_UMI:BAM_SORT_STATS_SAMTOOLS:BAM_STATS_SAMTOOLS [BAM_STATS_SAMTOOLS]"
    v35(["SAMTOOLS_STATS"])
    v38(["SAMTOOLS_FLAGSTAT"])
    v41(["SAMTOOLS_IDXSTATS"])
    end
    v34(( ))
    end
    subgraph "BAM_DEDUP_UMI:BAM_DEDUP_STATS_SAMTOOLS_UMITOOLS_TRANSCRIPTOME [BAM_DEDUP_STATS_SAMTOOLS_UMITOOLS_TRANSCRIPTOME]"
    v46(["UMITOOLS_DEDUP"])
    v49(["SAMTOOLS_INDEX"])
    subgraph "BAM_DEDUP_UMI:BAM_DEDUP_STATS_SAMTOOLS_UMITOOLS_TRANSCRIPTOME:BAM_STATS_SAMTOOLS [BAM_STATS_SAMTOOLS]"
    v53(["SAMTOOLS_STATS"])
    v55(["SAMTOOLS_FLAGSTAT"])
    v57(["SAMTOOLS_IDXSTATS"])
    end
    v51(( ))
    end
    v67(["SAMTOOLS_SORT"])
    v74(["UMITOOLS_PREPAREFORRSEM"])
    v44(( ))
    v59(( ))
    v61(( ))
    v63(( ))
    v72(( ))
    v79(( ))
    v84(( ))
    v89(( ))
    v91(( ))
    v93(( ))
    end
    v0 --> v1
    v2 --> v3
    v4 --> v5
    v6 --> v7
    v8 --> v9
    v10 --> v12
    v11 --> v12
    v12 --> v14
    v12 --> v13
    v12 --> v16
    v12 --> v59
    v12 --> v61
    v12 --> v63
    v12 --> v79
    v12 --> v84
    v14 --> v15
    v14 --> v16
    v17 --> v18
    v16 --> v18
    v18 --> v19
    v18 --> v79
    v18 --> v84
    v18 --> v89
    v16 --> v20
    v20 --> v21
    v20 --> v79
    v20 --> v84
    v20 --> v91
    v16 --> v22
    v22 --> v23
    v22 --> v79
    v22 --> v84
    v22 --> v93
    v24 --> v27
    v24 --> v35
    v25 --> v27
    v26 --> v27
    v27 --> v32
    v27 --> v31
    v27 --> v30
    v27 --> v29
    v27 --> v28
    v27 --> v34
    v27 --> v44
    v32 --> v33
    v32 --> v34
    v32 --> v44
    v34 --> v35
    v35 --> v37
    v35 --> v36
    v34 --> v38
    v38 --> v40
    v38 --> v39
    v34 --> v41
    v41 --> v43
    v41 --> v42
    v45 --> v46
    v44 --> v46
    v46 --> v49
    v46 --> v48
    v46 --> v47
    v46 --> v67
    v46 --> v51
    v46 --> v59
    v46 --> v61
    v46 --> v63
    v49 --> v50
    v49 --> v51
    v52 --> v53
    v51 --> v53
    v53 --> v54
    v53 --> v89
    v51 --> v55
    v55 --> v56
    v55 --> v91
    v51 --> v57
    v57 --> v58
    v57 --> v93
    v59 --> v60
    v61 --> v62
    v63 --> v64
    v65 --> v67
    v66 --> v67
    v67 --> v71
    v67 --> v70
    v67 --> v69
    v67 --> v68
    v67 --> v72
    v72 --> v74
    v74 --> v76
    v74 --> v75
    v74 --> v72
    v72 --> v78
    v79 --> v83
    v84 --> v88
    v89 --> v90
    v91 --> v92
    v93 --> v94
