flowchart TB
    subgraph " "
    v0["channel.fromPath"]
    v3["channel.fromPath"]
    v13["channel.empty"]
    end
    v5(["CUSTOM_RSEMMERGECOUNTS"])
    subgraph " "
    v6[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    v10[" "]
    v11[" "]
    v12[" "]
    v14[" "]
    end
    v1(( ))
    v4(( ))
    v0 --> v1
    v3 --> v4
    v1 --> v5
    v4 --> v5
    v5 --> v12
    v5 --> v11
    v5 --> v10
    v5 --> v9
    v5 --> v8
    v5 --> v7
    v5 --> v6
    v13 --> v14
