flowchart TB
    subgraph " "
    v0["vcf_ch"]
    v1["bed"]
    v2["diff_variant_file"]
    v67["channel.empty"]
    end
    v3(["VCFTOOLS"])
    subgraph " "
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    v10[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v16[" "]
    v17[" "]
    v18[" "]
    v19[" "]
    v20[" "]
    v21[" "]
    v22[" "]
    v23[" "]
    v24[" "]
    v25[" "]
    v26[" "]
    v27[" "]
    v28[" "]
    v29[" "]
    v30[" "]
    v31[" "]
    v32[" "]
    v33[" "]
    v34[" "]
    v35[" "]
    v36[" "]
    v37[" "]
    v38[" "]
    v39[" "]
    v40[" "]
    v41[" "]
    v42[" "]
    v43[" "]
    v44[" "]
    v45[" "]
    v46[" "]
    v47[" "]
    v48[" "]
    v49[" "]
    v50[" "]
    v51[" "]
    v52[" "]
    v53[" "]
    v54[" "]
    v55[" "]
    v56[" "]
    v57[" "]
    v58[" "]
    v59[" "]
    v60[" "]
    v61[" "]
    v62[" "]
    v63[" "]
    v64[" "]
    v65[" "]
    v66[" "]
    v68[" "]
    end
    v0 --> v3
    v1 --> v3
    v2 --> v3
    v3 --> v66
    v3 --> v65
    v3 --> v64
    v3 --> v63
    v3 --> v62
    v3 --> v61
    v3 --> v60
    v3 --> v59
    v3 --> v58
    v3 --> v57
    v3 --> v56
    v3 --> v55
    v3 --> v54
    v3 --> v53
    v3 --> v52
    v3 --> v51
    v3 --> v50
    v3 --> v49
    v3 --> v48
    v3 --> v47
    v3 --> v46
    v3 --> v45
    v3 --> v44
    v3 --> v43
    v3 --> v42
    v3 --> v41
    v3 --> v40
    v3 --> v39
    v3 --> v38
    v3 --> v37
    v3 --> v36
    v3 --> v35
    v3 --> v34
    v3 --> v33
    v3 --> v32
    v3 --> v31
    v3 --> v30
    v3 --> v29
    v3 --> v28
    v3 --> v27
    v3 --> v26
    v3 --> v25
    v3 --> v24
    v3 --> v23
    v3 --> v22
    v3 --> v21
    v3 --> v20
    v3 --> v19
    v3 --> v18
    v3 --> v17
    v3 --> v16
    v3 --> v15
    v3 --> v14
    v3 --> v13
    v3 --> v12
    v3 --> v11
    v3 --> v10
    v3 --> v9
    v3 --> v8
    v3 --> v7
    v3 --> v6
    v3 --> v5
    v3 --> v4
    v67 --> v68
