flowchart TB
    subgraph " "
    v0["in_ch"]
    v1["fasta"]
    v2["fai"]
    v3["dict"]
    v4["output_suffix"]
    v10["channel.empty"]
    end
    v5(["GATK4SPARK_APPLYBQSR"])
    subgraph " "
    v6[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    v11[" "]
    end
    v0 --> v5
    v1 --> v5
    v2 --> v5
    v3 --> v5
    v4 --> v5
    v5 --> v9
    v5 --> v8
    v5 --> v7
    v5 --> v6
    v10 --> v11
