flowchart TB
    subgraph " "
    v0[" "]
    v4["vcf_ch"]
    end
    v1(["SNPSIFT_ANNMEMCREATE"])
    subgraph " "
    v2[" "]
    v6[" "]
    v7[" "]
    v8[" "]
    end
    v5(["SNPSIFT_ANNMEM"])
    v3(( ))
    v0 --> v1
    v1 --> v2
    v1 --> v3
    v4 --> v5
    v3 --> v5
    v5 --> v8
    v5 --> v7
    v5 --> v6
