flowchart TB
    subgraph " "
    v0["fasta_ch"]
    v3["bam_ch"]
    v4["bai_ch"]
    v5["snp_ch"]
    end
    v1(["BISCUIT_INDEX"])
    subgraph " "
    v2[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    end
    v6(["BISCUIT_EPIREAD"])
    v0 --> v1
    v0 --> v6
    v1 --> v6
    v1 --> v2
    v3 --> v6
    v4 --> v6
    v5 --> v6
    v6 --> v9
    v6 --> v8
    v6 --> v7
