flowchart TB
    subgraph " "
    v0["channel.fromFilePairs"]
    v2["length"]
    end
    v3(["RIBODETECTOR"])
    subgraph " "
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    end
    v1(( ))
    v0 --> v1
    v2 --> v3
    v1 --> v3
    v3 --> v7
    v3 --> v6
    v3 --> v5
    v3 --> v4
