flowchart TB
    subgraph " "
    v0["in_ch"]
    v6["channel.empty"]
    end
    v1(["PLINK2_VCF2BGEN"])
    subgraph " "
    v2[" "]
    v3[" "]
    v4[" "]
    v5[" "]
    v7[" "]
    end
    v0 --> v1
    v1 --> v5
    v1 --> v4
    v1 --> v3
    v1 --> v2
    v6 --> v7
