flowchart TB
    subgraph " "
    v0["channel.fromPath"]
    v5["channel.of"]
    v6["gtf"]
    v7["chromosomes"]
    v8["fragment_length"]
    v9["fragment_length_sd"]
    end
    v2(["KALLISTO_INDEX"])
    subgraph " "
    v3[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    v14[" "]
    end
    v10(["KALLISTO_QUANT"])
    v1(( ))
    v4(( ))
    v0 --> v1
    v1 --> v2
    v2 --> v3
    v2 --> v4
    v5 --> v10
    v6 --> v10
    v7 --> v10
    v8 --> v10
    v9 --> v10
    v4 --> v10
    v10 --> v14
    v10 --> v13
    v10 --> v12
    v10 --> v11
