flowchart TB
    subgraph " "
    v0["in_ch"]
    v4["channel.empty"]
    end
    v1(["SYLPH_SKETCHSAMPLES"])
    subgraph " "
    v2[" "]
    v3[" "]
    v5[" "]
    end
    v0 --> v1
    v1 --> v3
    v1 --> v2
    v4 --> v5
