flowchart TB
    subgraph " "
    v0["in_ch"]
    v1["fasta_ch"]
    v2["output_bam"]
    v3["summary_file"]
    v4["blocks_file"]
    v5["stats_file"]
    v6["haplotag_file"]
    v7["file_format"]
    v24["channel.empty"]
    end
    v8(["HIPHASE"])
    subgraph " "
    v9[" "]
    v10[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v16[" "]
    v17[" "]
    v18[" "]
    v19[" "]
    v20[" "]
    v21[" "]
    v22[" "]
    v23[" "]
    v25[" "]
    end
    v0 --> v8
    v1 --> v8
    v2 --> v8
    v3 --> v8
    v4 --> v8
    v5 --> v8
    v6 --> v8
    v7 --> v8
    v8 --> v23
    v8 --> v22
    v8 --> v21
    v8 --> v20
    v8 --> v19
    v8 --> v18
    v8 --> v17
    v8 --> v16
    v8 --> v15
    v8 --> v14
    v8 --> v13
    v8 --> v12
    v8 --> v11
    v8 --> v10
    v8 --> v9
    v24 --> v25
