flowchart TB
    subgraph " "
    v0["vcf_ch"]
    v1["fasta_ch"]
    v2["fai_ch"]
    v7["channel.empty"]
    end
    v3(["VT_NORMALIZE"])
    subgraph " "
    v4[" "]
    v5[" "]
    v6[" "]
    v8[" "]
    end
    v0 --> v3
    v1 --> v3
    v2 --> v3
    v3 --> v6
    v3 --> v5
    v3 --> v4
    v7 --> v8
