flowchart TB
    subgraph " "
    v0["reads_ch"]
    v1["names_to_filter"]
    v2["output_format"]
    v3["interleaved_output"]
    v8["channel.empty"]
    end
    v4(["BBMAP_FILTERBYNAME"])
    subgraph " "
    v5[" "]
    v6[" "]
    v7[" "]
    v9[" "]
    end
    v0 --> v4
    v1 --> v4
    v2 --> v4
    v3 --> v4
    v4 --> v7
    v4 --> v6
    v4 --> v5
    v8 --> v9
