flowchart TB
    subgraph " "
    v0["channel.fromPath"]
    v2["ch_fasta"]
    v6["channel.empty"]
    end
    v3(["SAMTOOLS_STATS"])
    subgraph " "
    v4[" "]
    v5[" "]
    v7[" "]
    end
    v1(( ))
    v0 --> v1
    v2 --> v3
    v1 --> v3
    v3 --> v5
    v3 --> v4
    v6 --> v7
