flowchart TB
    subgraph " "
    v0["channel.fromPath"]
    v2["channel.fromPath"]
    v7["channel.empty"]
    end
    v4(["QUALIMAP_RNASEQ"])
    subgraph " "
    v5[" "]
    v6[" "]
    v8[" "]
    end
    v1(( ))
    v3(( ))
    v0 --> v1
    v2 --> v3
    v1 --> v4
    v3 --> v4
    v4 --> v6
    v4 --> v5
    v7 --> v8
