flowchart TB
    subgraph " "
    v0["bed_ch"]
    v1["dict_ch"]
    v2["arguments_file"]
    v6["channel.empty"]
    end
    v3(["PICARD_BEDTOINTERVALLIST"])
    subgraph " "
    v4[" "]
    v5[" "]
    v7[" "]
    end
    v0 --> v3
    v1 --> v3
    v2 --> v3
    v3 --> v5
    v3 --> v4
    v6 --> v7
