flowchart TB
    subgraph " "
    v0["in_ch"]
    v1["primers"]
    v17["channel.empty"]
    end
    v2(["LIMA"])
    subgraph " "
    v3[" "]
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    v8[" "]
    v9[" "]
    v10[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v16[" "]
    v18[" "]
    end
    v0 --> v2
    v1 --> v2
    v2 --> v16
    v2 --> v15
    v2 --> v14
    v2 --> v13
    v2 --> v12
    v2 --> v11
    v2 --> v10
    v2 --> v9
    v2 --> v8
    v2 --> v7
    v2 --> v6
    v2 --> v5
    v2 --> v4
    v2 --> v3
    v17 --> v18
