flowchart TB
    subgraph " "
    v0["est_in"]
    v3["channel.of"]
    end
    v1(["VARLOCIRAPTOR_ESTIMATEALIGNMENTPROPERTIES"])
    subgraph " "
    v2[" "]
    v8[" "]
    v9[" "]
    end
    v7(["VARLOCIRAPTOR_PREPROCESS"])
    v4(( ))
    v0 --> v1
    v1 --> v2
    v1 --> v4
    v3 --> v4
    v4 --> v7
    v7 --> v9
    v7 --> v8
