flowchart TB
    subgraph " "
    v0["in_ch"]
    v1["fasta"]
    v5["channel.empty"]
    end
    v2(["FREYJA_VARIANTS"])
    subgraph " "
    v3[" "]
    v4[" "]
    v6[" "]
    end
    v0 --> v2
    v1 --> v2
    v2 --> v4
    v2 --> v3
    v5 --> v6
