flowchart TB
    subgraph " "
    v0["fasta_ch"]
    v3["reads_ch"]
    end
    v1(["BISCUIT_INDEX"])
    subgraph " "
    v2[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    v8[" "]
    end
    v4(["BISCUIT_ALIGN"])
    v0 --> v1
    v0 --> v4
    v1 --> v4
    v1 --> v2
    v3 --> v4
    v4 --> v8
    v4 --> v7
    v4 --> v6
    v4 --> v5
