flowchart TB
    subgraph " "
    v0["empty_ch"]
    v1["bam_ch"]
    v2["blacklist_ch"]
    end
    v3(["DEEPTOOLS_BAMCOVERAGE"])
    subgraph " "
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    end
    v0 --> v3
    v1 --> v3
    v2 --> v3
    v3 --> v7
    v3 --> v6
    v3 --> v5
    v3 --> v4
