flowchart TB
    subgraph " "
    v0["bam_ch"]
    v1["ref_ch"]
    v2["split_to_N_reads"]
    v3["split_to_N_files"]
    v4["arguments_file"]
    v8["channel.empty"]
    end
    v5(["PICARD_SPLITSAMBYNUMBEROFREADS"])
    subgraph " "
    v6[" "]
    v7[" "]
    v9[" "]
    end
    v0 --> v5
    v1 --> v5
    v2 --> v5
    v3 --> v5
    v4 --> v5
    v5 --> v7
    v5 --> v6
    v8 --> v9
