flowchart TB
    subgraph " "
    v0["channel.fromFilePairs"]
    v9["channel.empty"]
    end
    v2(["TRIMGALORE"])
    subgraph " "
    v3[" "]
    v4[" "]
    v5[" "]
    v6[" "]
    v7[" "]
    v8[" "]
    v10[" "]
    end
    v1(( ))
    v0 --> v1
    v1 --> v2
    v2 --> v8
    v2 --> v7
    v2 --> v6
    v2 --> v5
    v2 --> v4
    v2 --> v3
    v9 --> v10
